import { Driver, Team, RaceResult } from '../types';

export const mockDrivers: Driver[] = [
  {
    id: 1,
    number: 44,
    firstName: 'Lewis',
    lastName: 'Hamilton',
    code: 'HAM',
    team: 'Mercedes',
    nationality: 'British',
    points: 4500,
    wins: 103,
    podiums: 197,
    championships: 7,
    avatar: 'https://example.com/hamilton.jpg',
    championshipYears: [2008, 2014, 2015, 2017, 2018, 2019, 2020],
  },
  {
    id: 2,
    number: 1,
    firstName: 'Max',
    lastName: 'Verstappen',
    code: 'VER',
    team: 'Red Bull Racing',
    nationality: 'Dutch',
    points: 2800,
    wins: 61,
    podiums: 111,
    championships: 4,
    avatar: 'https://example.com/verstappen.jpg',
    championshipYears: [2021, 2022, 2023, 2024],
  },
  {
    id: 3,
    number: 16,
    firstName: 'Charles',
    lastName: 'Leclerc',
    code: 'LEC',
    team: 'Ferrari',
    nationality: 'Monegasque',
    points: 1200,
    wins: 8,
    podiums: 35,
    championships: 0,
    avatar: 'https://example.com/leclerc.jpg',
  },
  {
    id: 4,
    number: 4,
    firstName: 'Lando',
    lastName: 'Norris',
    code: 'NOR',
    team: 'McLaren',
    nationality: 'British',
    points: 900,
    wins: 4,
    podiums: 22,
    championships: 0,
    avatar: 'https://example.com/norris.jpg',
  },
  {
    id: 5,
    number: 81,
    firstName: 'Oscar',
    lastName: 'Piastri',
    code: 'PIA',
    team: 'McLaren',
    nationality: 'Australian',
    points: 400,
    wins: 2,
    podiums: 10,
    championships: 0,
    avatar: 'https://example.com/piastri.jpg',
  },
];

export const mockTeams: Team[] = [
  {
    name: 'Red Bull Racing',
    fullName: 'Oracle Red Bull Racing',
    points: 8900,
    wins: 122,
    podiums: 280,
    championships: 6,
    championshipYears: [2022, 2023, 2024, 2013, 2012, 2011],
    color: '#3671c6',
    logo: 'https://example.com/redbull.png',
  },
  {
    name: 'Mercedes',
    fullName: 'Mercedes-AMG PETRONAS F1 Team',
    points: 7500,
    wins: 125,
    podiums: 300,
    championships: 8,
    championshipYears: [2021, 2020, 2019, 2018, 2017, 2016, 2015, 2014],
    color: '#27f4d2',
    logo: 'https://example.com/mercedes.png',
  },
  {
    name: 'Ferrari',
    fullName: 'Scuderia Ferrari',
    points: 9800,
    wins: 243,
    podiums: 810,
    championships: 16,
    championshipYears: [2008, 2007, 2004, 2003, 2002, 2001, 2000, 1999, 1998, 1997, 1996, 1995, 1994, 1993, 1992, 1991],
    color: '#e8002d',
    logo: 'https://example.com/ferrari.png',
  },
  {
    name: 'McLaren',
    fullName: 'McLaren F1 Team',
    points: 6200,
    wins: 183,
    podiums: 510,
    championships: 8,
    championshipYears: [1998, 1997, 1996, 1995, 1994, 1993, 1992, 1991],
    color: '#e10600',
    logo: 'https://example.com/mclaren.png',
  },
];

export const mockRaceResults: RaceResult[] = [
  {
    position: 1,
    number: 1,
    firstName: 'Max',
    lastName: 'Verstappen',
    code: 'VER',
    team: 'Red Bull Racing',
    laps: 57,
    time: '1:30:45.123',
    points: 25,
    url: '/results/2024/races/bahrain/bahrain-grand-prix',
    season: 2024,
    grandPrix: 'Bahrain Grand Prix',
    circuit: 'Bahrain International Circuit',
    date: '2024-03-02',
  },
  {
    position: 2,
    number: 16,
    firstName: 'Charles',
    lastName: 'Leclerc',
    code: 'LEC',
    team: 'Ferrari',
    laps: 57,
    time: '+22.457',
    points: 18,
    url: '/results/2024/races/bahrain/bahrain-grand-prix',
    season: 2024,
    grandPrix: 'Bahrain Grand Prix',
    circuit: 'Bahrain International Circuit',
    date: '2024-03-02',
  },
  {
    position: 3,
    number: 4,
    firstName: 'Lando',
    lastName: 'Norris',
    code: 'NOR',
    team: 'McLaren',
    laps: 57,
    time: '+25.654',
    points: 15,
    url: '/results/2024/races/bahrain/bahrain-grand-prix',
    season: 2024,
    grandPrix: 'Bahrain Grand Prix',
    circuit: 'Bahrain International Circuit',
    date: '2024-03-02',
  },
  {
    position: 1,
    number: 1,
    firstName: 'Max',
    lastName: 'Verstappen',
    code: 'VER',
    team: 'Red Bull Racing',
    laps: 50,
    time: '1:25:30.456',
    points: 25,
    url: '/results/2024/races/saudi-arabia/saudi-arabian-grand-prix',
    season: 2024,
    grandPrix: 'Saudi Arabian Grand Prix',
    circuit: 'Jeddah Corniche Circuit',
    date: '2024-03-09',
  },
  {
    position: 2,
    number: 11,
    firstName: 'Sergio',
    lastName: 'Perez',
    code: 'PER',
    team: 'Red Bull Racing',
    laps: 50,
    time: '+13.643',
    points: 18,
    url: '/results/2024/races/saudi-arabia/saudi-arabian-grand-prix',
    season: 2024,
    grandPrix: 'Saudi Arabian Grand Prix',
    circuit: 'Jeddah Corniche Circuit',
    date: '2024-03-09',
  },
  {
    position: 1,
    number: 44,
    firstName: 'Lewis',
    lastName: 'Hamilton',
    code: 'HAM',
    team: 'Mercedes',
    laps: 52,
    time: '1:33:56.123',
    points: 25,
    url: '/results/2023/races/britain/british-grand-prix',
    season: 2023,
    grandPrix: 'British Grand Prix',
    circuit: 'Silverstone Circuit',
    date: '2023-07-09',
  },
];
